# Generated by Django 6.1.1 on 2026-09-21 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_amenity_destinationamenity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['category'], name='destination_category_idx'),
        ),
    ]
