# Generated by Django 6.1.1 on 2026-09-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_destination_category_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='destinations', through='destinations.DestinationAmenity', to='destinations.amenity'),
        ),
    ]
