# Generated by Django 6.1.1 on 2026-09-21 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['status'], name='itinerary_status_idx'),
        ),
    ]
