# Generated by Django 6.1.1 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itinerary_itinerary_status_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='itineraries/'),
        ),
    ]
