# Generated by Django 6.1.1 on 2026-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('destinations', '0002_amenity_destinationamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_destinations',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='destinations.destination'),
        ),
    ]
